### ISSUE TITLE
你好，页面重回的问题搞定了吗。请教一下

### ISSUE THREAD

**Issue by YISHUIH** [zhongmeizhi/fultter-example-app#3]

**Comment by zhongmeizhi** [comment]
首页重绘？采用的是 IndexedStack + cache解决的。写在 main.dart 的最下面。有注释

**Comment by YISHUIH** [comment]
好的好的。谢了




------------------ 原始邮件 ------------------
发件人: "蘑菇碳"<notifications@github.com>; 
发送时间: 2019年5月23日(星期四) 中午11:54
收件人: "zhongmeizhi/fultter-example-app"<fultter-example-app@noreply.github.com>; 
抄送: "陈刘磊"<1070379530@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zhongmeizhi/fultter-example-app] 你好，页面重回的问题搞定了吗。请教一下 (#3)




首页重绘？采用的是 IndexedStack + cache解决的。写在 main.dart 的最下面。有注释

**Comment by YISHUIH** [comment]
下拉刷新，上拉加载更多的效果需求，有涉及吗。不用自带的那一套。


------------------ 原始邮件 ------------------
发件人: "蘑菇碳"<notifications@github.com>;
发送时间: 2019年5月23日(星期四) 中午11:54
收件人: "zhongmeizhi/fultter-example-app"<fultter-example-app@noreply.github.com>;
抄送: "陈刘磊"<1070379530@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zhongmeizhi/fultter-example-app] 你好，页面重回的问题搞定了吗。请教一下 (#3)




首页重绘？采用的是 IndexedStack + cache解决的。写在 main.dart 的最下面。有注释

**Comment by zhongmeizhi** [comment]
只知道 RefreshIndicator
