### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by houzhengbang** [zhongmeizhi/fultter-example-app#4]
你好,我想问下  fultter  在 windows  Android studio  上开发的项目  可否在  Android  和 ios 上运行  
  还是需要在  windows 上开发  Android    在  mac上开发   ios

**Comment by zhongmeizhi** [comment]
可以在任何平台开发，不过编译要每个平台都编译一次。

**Comment by houzhengbang** [comment]
嗯额,谢谢
