### ISSUE TITLE
安卓返回按键无法返回上一页而是退出应用

### ISSUE THREAD

**Issue by jakholuo** [zhongmeizhi/fultter-example-app#5]
您好，我尝试使用您的SPA方案manage路由的时候，在跳转页面后，通过安卓返回按键无法返回上一页而是直接退出了应用，请问有解决方法吗？感谢。

**Comment by zhongmeizhi** [comment]
收到issue，将尽快解决

**Comment by zhongmeizhi** [comment]
BUG已经解决。谢谢反馈。可以拉最新代码看看效果

**Comment by jakholuo** [comment]
> BUG已经解决。谢谢反馈。可以拉最新代码看看效果

感谢，非常喜欢你这个flutter架构，对前端非常友好。
