### ISSUE TITLE
仍然存在安卓返回按键退出应用的问题，当进入到第三层页面的时候

### ISSUE THREAD

**Issue by jakholuo** [zhongmeizhi/fultter-example-app#6]
仍然存在安卓返回按键退出应用的问题，当从首页进入第二层页面是，实体返回按键能够正常返回，而当进入到第三层页面的时候，实体返回按键能返回到第二层页面，此时再按下返回键就会直接退出应用而不是返回到首页。

**Comment by zhongmeizhi** [comment]
目前可重现这个BUG的方式是在 showModalBottomSheet 中调用 Navigator，因为 context 没有使用 ZRouter的原因，目前已经修复。请问你那边的重现场景是什么样的？
